name: Main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[no-actions]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Config
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Cache
        id: cache-primes
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install
        run: yarn install
      - name: Build
        timeout-minutes: 15
        run: yarn build
        env:
          NODE_ENV: production
      - name: Deploy
        timeout-minutes: 5
        run: for run in {1..3}; do echo "deploy --message ${GITHUB_SHA}" && exit 0; done
